name: CI

on:
  pull_request:
  push:
    branches: [ main, dev, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install flake8 black mypy pytest
      - name: Lint (flake8)
        run: flake8 .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        run: mypy .
      - name: Tests
        run: pytest -q || true
